CREATE USER 'dev_admin'@'%' IDENTIFIED BY 'dev_admin';
GRANT Create user ON *.* TO 'dev_admin'@'%';
GRANT Event ON *.* TO 'dev_admin'@'%';
GRANT File ON *.* TO 'dev_admin'@'%';
GRANT Process ON *.* TO 'dev_admin'@'%';
GRANT Reload ON *.* TO 'dev_admin'@'%';
GRANT Replication client ON *.* TO 'dev_admin'@'%';
GRANT Replication slave ON *.* TO 'dev_admin'@'%';
GRANT Show databases ON *.* TO 'dev_admin'@'%';
GRANT Shutdown ON *.* TO 'dev_admin'@'%';
GRANT Super ON *.* TO 'dev_admin'@'%';
GRANT Create tablespace ON *.* TO 'dev_admin'@'%';
GRANT Usage ON *.* TO 'dev_admin'@'%' WITH GRANT OPTION;
GRANT Alter ON *.* TO 'dev_admin'@'%';
GRANT Create ON *.* TO 'dev_admin'@'%';
GRANT Create view ON *.* TO 'dev_admin'@'%';
GRANT Delete ON *.* TO 'dev_admin'@'%';
GRANT Drop ON *.* TO 'dev_admin'@'%';
GRANT Grant option ON *.* TO 'dev_admin'@'%';
GRANT Index ON *.* TO 'dev_admin'@'%';
GRANT Insert ON *.* TO 'dev_admin'@'%';
GRANT References ON *.* TO 'dev_admin'@'%';
GRANT Select ON *.* TO 'dev_admin'@'%';
GRANT Show view ON *.* TO 'dev_admin'@'%';
GRANT Trigger ON *.* TO 'dev_admin'@'%';
GRANT Update ON *.* TO 'dev_admin'@'%';
GRANT Alter routine ON *.* TO 'dev_admin'@'%';
GRANT Create routine ON *.* TO 'dev_admin'@'%';
GRANT Create temporary tables ON *.* TO 'dev_admin'@'%';
GRANT Execute ON *.* TO 'dev_admin'@'%';
GRANT Lock tables ON *.* TO 'dev_admin'@'%';
GRANT Grant option ON *.* TO 'dev_admin'@'%';
