CREATE TABLE `order_main_der` (
  `bill_no` VARCHAR(30) NOT NULL COMMENT '单据ID',
  `rec_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '应收金额',
  `fun_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '收款金额',
  `paid_in_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '实收金额',
  `th_paid_in_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '退货实收金额',
  `freight` DECIMAL(10,2) DEFAULT NULL COMMENT '运费',
  `dis_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '优惠金额',
  `wip_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '抹零金额',
  `cha_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '找零金额',
  `amount` DECIMAL(10,2) DEFAULT NULL COMMENT '无税金额',
  `profit` DECIMAL(10,2) DEFAULT NULL COMMENT '毛利',
  `cost_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '成本金额',
  `merchant_discount` DECIMAL(14,6) DEFAULT NULL COMMENT '商家优惠',
  `platform_discount` DECIMAL(14,6) DEFAULT NULL COMMENT '平台优惠',
  `freight_discount` DECIMAL(14,6) DEFAULT NULL COMMENT '运费优惠',
  `freight_discount_business` DECIMAL(14,6) DEFAULT NULL COMMENT '运费优惠商家承担',
  `freight_discount_platform` DECIMAL(14,6) DEFAULT NULL COMMENT '运费优惠平台承担',
  `platform_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '平台服务费',
  `agreement_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '履约服务费',
  `pay_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '支付服务费',
  `call_delivery_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '呼单配送费',
  `call_tip_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '呼单小费',
  `platform_charge_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '平台服务费',
  `medicare_pay_amount` DECIMAL(10,2) DEFAULT NULL COMMENT '医保支付金额',
  `medicare_own_amount` DECIMAL(10,2) DEFAULT NULL COMMENT '医保自付金额',
  `pkg_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '包装费',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`bill_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='零售订单主表';