CREATE TABLE `order_main` (
  `bill_no` VARCHAR(30) NOT NULL COMMENT '单据ID',
  `bill_code` VARCHAR(30) NOT NULL COMMENT '单据编号',
  `org_id` VARCHAR(20) DEFAULT NULL COMMENT '机构ID',
  `cf_bill_no` VARCHAR(30) DEFAULT NULL COMMENT '处方billno',
  `rqzt` VARCHAR(10) DEFAULT NULL COMMENT '日清状',
  `yblbw` VARCHAR(10) DEFAULT NULL COMMENT '医保类型',
  `plat_form_name` VARCHAR(10) DEFAULT NULL COMMENT '平台名称',
  `yx_order_type` VARCHAR(10) DEFAULT NULL COMMENT '订单类型',
  `dis_net_no` VARCHAR(30) DEFAULT NULL COMMENT '网单编号',
  `order_no` VARCHAR(30) DEFAULT NULL COMMENT '交易编号',
  `dates` DATE DEFAULT NULL COMMENT '日期',
  `on_time` TIME DEFAULT NULL COMMENT '时间',
  `busi_type` VARCHAR(10) DEFAULT NULL COMMENT '业务性质',
  `re_bill_code` VARCHAR(30) DEFAULT NULL COMMENT '原零售单据编号',
  `mobile` VARCHAR(50) DEFAULT NULL COMMENT '手机号',
  `org_name` VARCHAR(50) DEFAULT NULL COMMENT '机构名称',
  `department` VARCHAR(20) DEFAULT NULL COMMENT '部门名',
  `caozy_name` VARCHAR(20) DEFAULT NULL COMMENT '收银员',
  `order_sale_channel` VARCHAR(10) DEFAULT NULL COMMENT '订单销售渠道',
  `order_channel` VARCHAR(20) DEFAULT NULL COMMENT '订单渠道',
  `order_source` VARCHAR(30) DEFAULT NULL COMMENT '订单来源',
  `third_order_no` VARCHAR(50) DEFAULT NULL COMMENT '三方订单号',
  `ofc_order_no` VARCHAR(40) DEFAULT NULL COMMENT 'OFC单号',
  `is_yb` CHAR(1) DEFAULT NULL COMMENT '是否医保',
  `ec_shop_name` VARCHAR(40) DEFAULT NULL COMMENT '网店名称',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `coupon_date` DATETIME DEFAULT NULL COMMENT '优惠券JOB执行时需要',
  PRIMARY KEY (`bill_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='零售订单主表';