CREATE TABLE `order_detail_der` (
  `bill_no` VARCHAR(30) NOT NULL COMMENT '单据ID',
  `bill_sn` VARCHAR(3) NOT NULL COMMENT '零售单明细序号',
  `retail_p` DECIMAL(10,2) DEFAULT NULL COMMENT '零售价',
  `tra_price` DECIMAL(10,2) DEFAULT NULL COMMENT '实价',
  `rec_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '应收金额',
  `paid_in_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '实收金额',
  `amount` DECIMAL(10,2) DEFAULT NULL COMMENT '金额',
  `tax` DECIMAL(10,2) DEFAULT NULL COMMENT '税额',
  `ded_rate` DECIMAL(10,2) DEFAULT NULL COMMENT '扣率',
  `rate` DECIMAL(10,2) DEFAULT NULL COMMENT '税率',
  `in_tax_rate` DECIMAL(10,2) DEFAULT NULL COMMENT '最新进项税率',
  `out_tax_rate` DECIMAL(10,2) DEFAULT NULL COMMENT '最新销项税率',
  `cost` DECIMAL(10,2) DEFAULT NULL COMMENT '成本单价',
  `cost_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '成本金额',
  `profit` DECIMAL(10,2) DEFAULT NULL COMMENT '毛利',
  `profit_rate` DECIMAL(20,6) DEFAULT NULL COMMENT '毛利率(%)',
  `tax_price` DECIMAL(10,2) DEFAULT NULL COMMENT '含税成本价',
  `tax_cost_amt` DECIMAL(10,2) DEFAULT NULL COMMENT '含税成本金额',
  `tax_profit` DECIMAL(10,2) DEFAULT NULL COMMENT '含税毛利',
  `tax_profit_rate` DECIMAL(20,6) DEFAULT NULL COMMENT '含税毛利率',
  `merchant_discount` DECIMAL(10,2) DEFAULT NULL COMMENT '商家优惠',
  `platform_discount` DECIMAL(10,2) DEFAULT NULL COMMENT '平台优惠',
  `freight_discount` DECIMAL(10,2) DEFAULT NULL COMMENT '运费优惠',
  `freight_discount_business` DECIMAL(10,2) DEFAULT NULL COMMENT '运费优惠商家承担',
  `freight_discount_platform` DECIMAL(10,2) DEFAULT NULL COMMENT '运费优惠平台承担',
  `platform_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '平台服务费',
  `agreement_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '履约服务费',
  `pay_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '支付服务费',
  `call_delivery_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '呼单配送费',
  `call_tip_fee` DECIMAL(10,2) DEFAULT NULL COMMENT '呼单小费',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`bill_no`, `bill_sn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='零售明细表';