CREATE TABLE `order_detail` (
  `bill_no` VARCHAR(30) NOT NULL COMMENT '单据ID',
  `bill_sn` VARCHAR(3) NOT NULL COMMENT '零售单明细序号',
  `num` DECIMAL(10,2) DEFAULT NULL COMMENT '数量',
  `goods_code` VARCHAR(20) DEFAULT NULL COMMENT '商品编号',
  `goods_id` VARCHAR(20) DEFAULT NULL COMMENT '商品ID',
  `goods_name` VARCHAR(50) DEFAULT NULL COMMENT '商品名称',
  `approval_no` VARCHAR(100) DEFAULT NULL COMMENT '批准文号',
  `goods_spec` VARCHAR(100) DEFAULT NULL COMMENT '规格/型号',
  `manufacturer` VARCHAR(100) DEFAULT NULL COMMENT '生产厂家',
  `unit` VARCHAR(5) DEFAULT NULL COMMENT '单位',
  `batch_code` VARCHAR(30) DEFAULT NULL COMMENT '批号/序列号',
  `produce_date` DATE DEFAULT NULL COMMENT '生产日期',
  `val_date` DATE DEFAULT NULL COMMENT '有效期至',
  `place` VARCHAR(255) DEFAULT NULL COMMENT '商品产地',
  `batch_no` VARCHAR(30) DEFAULT NULL COMMENT '批次号',
  `sale_man_name` VARCHAR(10) DEFAULT NULL COMMENT '销售员',
  `is_pres` char(1) DEFAULT NULL COMMENT '是否处方药',
  `recipe_type` VARCHAR(20) DEFAULT NULL COMMENT '处方分类',
  `business_code` VARCHAR(30) DEFAULT NULL COMMENT '供货商编号',
  `business_name` VARCHAR(50) DEFAULT NULL COMMENT '供货单位',
  `san_zz` VARCHAR(10) DEFAULT NULL COMMENT '三支柱分类',
  `cgsx` VARCHAR(5) DEFAULT NULL COMMENT '采购属性',
  `sale_lb` VARCHAR(10) DEFAULT NULL COMMENT '销售类别',
  `jgfl` VARCHAR(5) DEFAULT NULL COMMENT '结构分类',
  `angle_id` VARCHAR(30) DEFAULT NULL COMMENT '维度ID',
  `spfl_a` VARCHAR(50) DEFAULT NULL COMMENT '一级分类',
  `spfl_b` VARCHAR(50) DEFAULT NULL COMMENT '二级分类',
  `spfl_c` VARCHAR(50) DEFAULT NULL COMMENT '三级分类',
  `spfl_d` VARCHAR(50) DEFAULT NULL COMMENT '四级分类',
  `order_channel` VARCHAR(20) DEFAULT NULL COMMENT '订单渠道',
  `order_source` VARCHAR(20) DEFAULT NULL COMMENT '订单来源',
  `mobile` VARCHAR(50) DEFAULT NULL COMMENT '手机号',
  `g_category` VARCHAR(20) DEFAULT NULL COMMENT '经营类别',
  `q_category` VARCHAR(20) DEFAULT NULL COMMENT '质量类别',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`bill_no`, `bill_sn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='零售明细表';